### 로그인
POST http://localhost:8080/kakao/login
Content-Type: application/json

{
  "idToken": "eyJraWQiOiI5ZjI1MmRhZGQ1ZjIzM2Y5M2QyZmE1MjhkMTJmZWEiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIwMzA3MjY4NjE1MGZlYWFiMjUwMWU2M2UyMTgzZmY2NCIsInN1YiI6IjM1MTQwODc4MDEiLCJhdXRoX3RpbWUiOjE3MTc3MTEyMDEsImlzcyI6Imh0dHBzOi8va2F1dGgua2FrYW8uY29tIiwibmlja25hbWUiOiLtmansoJzssqAiLCJleHAiOjE3MTc3MzI4MDEsImlhdCI6MTcxNzcxMTIwMSwicGljdHVyZSI6Imh0dHA6Ly9rLmtha2FvY2RuLm5ldC9kbi9iYkpCaDAvYnRzam12T2ptdXAvUkFXenFnb3k1QVNwM1NxeFVOUWpWSy9pbWdfMTEweDExMC5qcGciLCJlbWFpbCI6Imdoa2R3cDAxOEBuYXZlci5jb20ifQ.JMVgGoBkgabb6y0diiOPVSR109wG1tGKdqJT8kEkUkYj9KMIAvV2gksIyFO2EWgUNVzpRPOeeiZEmVtMXiNHGM4rdV6naURCf3AY8wSGxjfzpZcOCla2fJEkK8CFYKK_t4CfOrfn2oJDmp4jdmrXIO_6xg6gGIsAfRF1kNkyebQtGf00Za-0V5t937PEerfcfIM86HPaBILeZGKhjLP7uZ8ynzUaJiH31x_HLIB2jc_9CG5WpqX6pin9t4cOlriFCnZNgoD4gH69pPJUuMewowcJHrj7AvYeIrcevNA4wJZuYi3Kp8sQpKXq00JEg8OgsKH2IE26eN-tpVz66C8MLQ"
}

### 로그인 한 상태로 인증 체크
GET http://localhost:8080/ping
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhaS1pbnRlcnZpZXctc2ltdWxhdG9yIiwic3ViIjoiZjBjNjQ2MGYtYTU2ZC00YjdmLTllZDQtMDVjNGU5YTgzOGQ3IiwiaWF0IjoxNzE3NzExMjExLCJleHAiOjE3MTc3MTIwNzUsInR5cGUiOiJhY2Nlc3NUb2tlbiIsInJvbGUiOiLsnbzrsJgg7Jyg7KCAIn0.YhA2hS3LoV0vvRI7utDwA-e5lepNyO99Bs6C-2GCszo

### 엑세스 토큰 재발급
POST http://localhost:8080/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhaS1pbnRlcnZpZXctc2ltdWxhdG9yIiwic3ViIjoiODVkMTFiYzAtMjYzZS00NjA2LWE5NjgtZDI5NGY4MWEwODVhIiwiaWF0IjoxNzE3NjMxNzE3LCJleHAiOjE3MTc2MzI1ODEsInR5cGUiOiJyZWZyZXNoVG9rZW4iLCJyb2xlIjoi7J2867CYIOycoOyggCJ9.55mfXi0PfSpcfKe9iFW6gzWmCTDegH5-LtkwxKIgs5k"
}
